spring.application.name=banking-monolith

# 1. Enable the H2 web console so we can view our tables in the browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 2. Database Connection Settings
spring.datasource.url=jdbc:h2:mem:bankingdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update

# For learning purpose only because it will log the sql into the terminal.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
